<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->text('ITEMID')->nullable();
            $table->longText('ITEMIMAGE')->nullable();
            $table->text('SuppRefNo')->nullable();
            $table->text('Suppliers_Ref_Number')->nullable();
            $table->text('ITEMNAME');
            $table->text('Search_Name')->nullable();
            $table->text('Parent_Item')->nullable();
            $table->text('PG_Percentage')->nullable();
            $table->text('Std_Weight_Pcs', 8, 2)->nullable();
            $table->text('Making_Code')->nullable();
            $table->text('Comp_Calc_Type')->nullable();
            $table->text('Making_Type')->nullable();
            $table->text('Sale_Calculation_Type_Gross')->nullable();
            $table->text('Item_Group')->nullable();
            $table->text('Item_Type')->nullable();
            $table->text('Flat_Rate')->nullable();
            $table->text('Pair_No')->nullable();
            $table->text('Hold')->nullable();
            $table->text('EJRL_Vend_Account')->nullable();
            $table->text('U_O_M')->nullable();
            $table->text('Article_Group')->nullable();
            $table->text('HUID_Number')->nullable();
            $table->text('Is_Consignment')->nullable();
            $table->text('EJ_Product_Type')->nullable();
            $table->text('SKU_Code')->nullable();
            $table->text('Label_Type')->nullable();
            $table->text('Exclude_Making_Disc')->nullable();
            $table->text('SKU_Description')->nullable();
            $table->text('Pcs')->nullable();
            $table->text('Dust')->nullable();
            $table->text('LOF_Wastage')->nullable();
            $table->text('Scrap')->nullable();
            $table->text('Loss')->nullable();
            $table->text('Ornament')->nullable();
            $table->text('Loose')->nullable();
            $table->text('Retail')->nullable();
            $table->text('Franchisee')->nullable();
            $table->text('Cost_Group')->nullable();
            $table->text('Inventory_Model_Group')->nullable();
            $table->text('Dimension_Group')->nullable();
            $table->text('Coverage_Group')->nullable();
            $table->text('Commission_Group')->nullable();
            $table->text('Batch_Number_Group')->nullable();
            $table->text('Serial_Number_Group')->nullable();
            $table->text('Buyer_Group')->nullable();
            $table->text('Packing_Group')->nullable();
            $table->text('Item_Price_Tolerance_Group')->nullable();
            $table->text('TCS_Trans_Type')->nullable();
            $table->text('Counting_Group')->nullable();
            $table->text('Default_Configuration')->nullable();
            $table->text('Default_Vendor')->nullable();
            $table->text('Configurable')->nullable();
            $table->text('Identical')->nullable();
            $table->text('Autocreate_Combinations')->nullable();
            $table->text('Use_Combination_Cost_Price')->nullable();
            $table->text('Size')->nullable();
            $table->text('Code')->nullable();
            $table->text('Batch_Number')->nullable();
            $table->text('Batch_Number_Sequence')->nullable();
            $table->text('Bulk_Receive_Batch_No_Sequence')->nullable();
            $table->text('Article_Code')->nullable();
            $table->text('Ingredient_Code')->nullable();
            $table->text('Gift_Amount')->nullable();
            $table->text('Silver_Name')->nullable();
            $table->text('Gender')->nullable();
            $table->text('Inventory_Unit')->nullable();
            $table->text('Volume')->nullable();
            $table->text('Packing_Quantity')->nullable();
            $table->text('Net_Weight')->nullable();
            $table->text('Tare_Weight')->nullable();
            $table->text('Gross_Depth')->nullable();
            $table->text('Gross_Width')->nullable();
            $table->text('Gross_Height')->nullable();
            $table->text('Sort_Code')->nullable();
            $table->text('Arrival_Handling_Time')->nullable();
            $table->text('Item_Tagging_Level')->nullable();
            $table->text('CZ_Item')->nullable();
            $table->text('Gift_Item')->nullable();
            $table->text('Apply_Credit_Card_Charges')->nullable();
            $table->text('Repair_Item')->nullable();
            $table->text('Purchase_Unit')->nullable();
            $table->text('Misc_Charges_Group')->nullable();
            $table->text('Item_Sales_Tax_Group')->nullable();
            $table->text('Overdelivery')->nullable();
            $table->text('Underdelivery')->nullable();
            $table->text('Intercompany_Stopped')->nullable();
            $table->text('BOM_Unit')->nullable();
            $table->text('Constant_Scrap')->nullable();
            $table->text('Variable_Scrap')->nullable();
            $table->text('Level')->nullable();
            $table->text('Phantom')->nullable();
            $table->text('Auto_Report_as_Finished')->nullable();
            $table->text('Sales_Unit')->nullable();
            $table->text('Production_Pool')->nullable();
            $table->text('Production_Group')->nullable();
            $table->text('Arrival')->nullable();
            $table->text('Flushing_Principle')->nullable();
            $table->text('Category')->nullable();
            $table->text('Calculation_Group')->nullable();
            $table->text('Stop_Explosion')->nullable();
            $table->text('Vendor')->nullable();
            $table->text('Service_Code')->nullable();
            $table->text('Price')->nullable();
            $table->text('Max_Retail_Price')->nullable();
            $table->text('Price_Unit')->nullable();
            $table->text('Price_Misc_Charges')->nullable();
            $table->text('Price_Quantity')->nullable();
            $table->text('Date_of_Price')->nullable();
            $table->text('Incl_in_Unit_Price')->nullable();
            $table->text('Line_Discount')->nullable();
            $table->text('Multiline_Discount')->nullable();
            $table->text('Total_Discount')->nullable();
            $table->text('Supplementary_Item_Group')->nullable();
            $table->text('Max_Weight_Pcs')->nullable();
            $table->text('Min_Weight_Pcs')->nullable();
            $table->text('Tolerance_Percentage')->nullable();
            $table->text('Company_Item')->nullable();
            $table->text('Use_')->nullable();
            $table->text('Alternative_Item_Number')->nullable();
            $table->text('Configuration')->nullable();
            $table->text('ABC_code_Value')->nullable();
            $table->text('ABC_code_Margin')->nullable();
            $table->text('ABC_code_Revenue')->nullable();
            $table->text('ABC_code_Carrying_Cost')->nullable();
            $table->text('Commodity')->nullable();
            $table->text('Additional_Units')->nullable();
            $table->text('Country_Region')->nullable();
            $table->text('State')->nullable();
            $table->text('Height')->nullable();
            $table->text('Width')->nullable();
            $table->text('Depth')->nullable();
            $table->text('Density')->nullable();
            $table->text('Department')->nullable();
            $table->text('Cost_Center')->nullable();
            $table->text('Purpose')->nullable();
            $table->text('Line_of_Business')->nullable();
            $table->text('Brand')->nullable();
            $table->text('Employee')->nullable();
            $table->text('Opening_Balance')->nullable();
            $table->text('Finishing_Type')->nullable();
            $table->text('Plating_Type')->nullable();
            $table->text('Product_Type')->nullable();
            $table->text('Setting_Type')->nullable();
            $table->text('Manufacturing_Type')->nullable();
            $table->text('Style')->nullable();
            $table->text('Theme')->nullable();
            $table->text('Collection')->nullable();
            $table->text('Product_Group')->nullable();
            $table->text('Product_Category')->nullable();
            $table->text('Class')->nullable();
            $table->text('Gold_Project_Types')->nullable();
            $table->text('Gender1')->nullable();
            $table->text('Weight_Range')->nullable();
            $table->text('Division')->nullable();
            $table->text('Weight_Band')->nullable();
            $table->text('Staple_Flag')->nullable();
            $table->text('New_SKU')->nullable();
            $table->text('Text')->nullable();
            $table->text('Sketch_ID')->nullable();
            $table->text('Total_Discount1')->nullable();
            $table->text('Sample_Item')->nullable();
            $table->string('FootFall_Trans_Type')->nullable();
            $table->string('Gross_Weight')->nullable();
            $table->string('Import_Tariff_Code')->nullable();
            $table->string('Export_Tariff_Code')->nullable();
            $table->string('Excise_Tariff_Code')->nullable();
            $table->string('Quality_Code')->nullable();
            $table->string('Diamond_Row_Code')->nullable();
            $table->string('Dial_Colour_Code')->nullable();
            $table->string('Strap_Material_Code')->nullable();
            $table->string('Strap_Colour_Code')->nullable();
            $table->string('Hand_Code')->nullable();
            $table->string('Type_Code')->nullable();
            $table->string('Watch_Complexity')->nullable();
            $table->string('Latest_Purchase_Price')->nullable();
            $table->string('Latest_Cost_Price')->nullable();
            $table->string('Sales_Price_Model')->nullable();
            $table->string('Base_Price')->nullable();
            $table->string('Contribution_Ratio')->nullable();
            $table->string('Misc_Charges_Pct')->nullable();
            $table->text('Name_Alias_Text')->nullable();
            $table->text('Silver_Category_Name')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}
